services:
  - type: web
    name: college-gatepass-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    plan: free
